### ISSUE TITLE
Add threshold for percentage of article content read before marking as read

### ISSUE THREAD

**Issue by uncenter** [isabelroses/izrss#27]
Currently once 80% of an article is viewed, the article is marked as read. Could be nice to have this as a configuration option?

**Comment by isabelroses** [comment]
This should be doable, i think.

**Comment by isabelroses** [comment]
Any preferences on the name of the option?

**Comment by isabelroses** [comment]
closed in 5b66fe606d3b9252a89144368aa628b2da6efee9
