### ISSUE TITLE
Marking all articles as read returns you to other (random?) feed

### ISSUE THREAD

**Issue by uncenter** [isabelroses/izrss#29]
Inside a feed's list of articles, pressing <kbd>X</kbd> to mark all feeds as read exits me out of the feed I am currently in and places me *not in the same feed I was just in* nor *in the list of feeds* but in some other random feed's list of articles - often the first, though if I mark all as read in the first or second it goes to the third? Not exactly sure what is going on but either way it seems very buggy. As I mentioned earlier keeping me in the same list of articles or returning to the list of feeds would be acceptable behavior.

https://github.com/isabelroses/izrss/assets/47499684/15b8d36b-a966-42a6-b42c-68c0990616e2

**Comment by isabelroses** [comment]
hum, seems to be a issue with the reloading phase.

**Comment by isabelroses** [comment]
Also is this uppercase or lowercase `x` or does it not matter?

**Comment by uncenter** [comment]
> Also is this uppercase or lowercase `x` or does it not matter?

Specifically uppercase <kbd>X</kbd> to mark *all* articles as read.

**Comment by isabelroses** [comment]
Thanks for all the details, made it really easy to find. closed by 94f9ce8
